# Generated by Django 3.2.4 on 2021-06-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('istruttoria', models.CharField(blank=True, max_length=30, null=True)),
                ('pos', models.CharField(blank=True, max_length=30, null=True)),
                ('data_prot_gen', models.CharField(blank=True, max_length=30, null=True)),
                ('prot_gen', models.CharField(blank=True, max_length=30, null=True)),
                ('prot_urb', models.CharField(blank=True, max_length=30, null=True)),
                ('num_atto', models.CharField(blank=True, max_length=30, null=True)),
                ('data_atto', models.CharField(blank=True, max_length=30, null=True)),
                ('atto', models.CharField(blank=True, max_length=30, null=True)),
                ('richiedente', models.CharField(blank=True, max_length=50, null=True)),
                ('l_nasc', models.CharField(blank=True, max_length=30, null=True)),
                ('d_nasc', models.CharField(blank=True, max_length=30, null=True)),
                ('citta', models.CharField(blank=True, max_length=30, null=True)),
                ('residenza', models.CharField(blank=True, max_length=30, null=True)),
                ('cod_fisc', models.CharField(blank=True, max_length=30, null=True)),
                ('oggetto', models.TextField(blank=True, null=True)),
                ('ubicazione', models.CharField(blank=True, max_length=30, null=True)),
                ('fg', models.CharField(blank=True, max_length=30, null=True)),
                ('mapp', models.CharField(blank=True, max_length=30, null=True)),
                ('com_edil', models.CharField(blank=True, max_length=30, null=True)),
                ('data_ce', models.CharField(blank=True, max_length=30, null=True)),
                ('tecnico', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
