# Generated by Django 3.2.4 on 2021-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='richiedente',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
