# Generated by Django 3.2.4 on 2021-07-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivi', '0002_alter_pratica_richiedente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='residenza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='tecnico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='ubicazione',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
