# Generated by Django 3.2.4 on 2021-07-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivi', '0003_auto_20210711_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='d_nasc',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_atto',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_ce',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_prot_gen',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
