# Generated by Django 3.2.4 on 2021-07-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivi', '0005_auto_20210714_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='d_nasc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_atto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_ce',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_prot_gen',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='residenza',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='tecnico',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='ubicazione',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
