# Generated by Django 3.2.4 on 2021-07-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivi', '0007_auto_20210714_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pratica',
            options={'verbose_name_plural': 'Pratiche'},
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_atto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
