# Generated by Django 3.2.5 on 2021-07-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivi', '0008_auto_20210717_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='data_prot_gen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='mapp',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
