# Generated by Django 3.2.5 on 2021-07-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivi', '0009_auto_20210724_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='tipo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
