# Generated by Django 3.2.5 on 2021-07-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivi', '0010_alter_pratica_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratica',
            name='data_crea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pratica',
            name='data_mod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='d_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data di nascita'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_atto',
            field=models.DateField(blank=True, null=True, verbose_name='Data atto'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_ce',
            field=models.DateField(blank=True, null=True, verbose_name='Data comm edil'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_prot_gen',
            field=models.DateField(blank=True, null=True, verbose_name='Data prot. gen.'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='l_nasc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Luogo di nascita'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='prot_gen',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Protocollo gen.'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='prot_urb',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Prot. Urb./SUAP'),
        ),
    ]
