# Generated by Django 3.2.5 on 2021-07-30 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archivi', '0011_auto_20210729_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254)),
                ('documento', models.FileField(upload_to='media')),
                ('data_crea', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_mod', models.DateTimeField(auto_now=True)),
                ('rif_pratica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archivi.pratica')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Allegati',
            },
        ),
    ]
