# Generated by Django 3.2.5 on 2021-07-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivi', '0012_allegato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allegato',
            name='username',
            field=models.CharField(max_length=80),
        ),
    ]
