# Generated by Django 3.2.5 on 2021-07-31 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivi', '0014_delete_allegato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome file')),
                ('doc', models.FileField(null=True, upload_to='media')),
                ('pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivi.pratica')),
            ],
            options={
                'verbose_name_plural': 'Allegati',
            },
        ),
    ]
