# Generated by Django 3.2.5 on 2021-08-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivi', '0016_remove_allegato_pratica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='d_nasc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data di nascita'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_atto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data atto'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_ce',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data comm edil'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_prot_gen',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data prot. gen.'),
        ),
    ]
