# Generated by Django 3.2.5 on 2021-08-01 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivi', '0017_auto_20210801_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegato',
            name='pratica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archivi.pratica'),
        ),
    ]
