# Generated by Django 3.2.5 on 2021-08-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivi', '0020_alter_allegato_pratica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allegato',
            name='doc',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='allegato',
            name='nome',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='nome file'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='d_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data di nascita'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_atto',
            field=models.DateField(blank=True, null=True, verbose_name='Data atto'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_ce',
            field=models.DateField(blank=True, null=True, verbose_name='Data comm edil'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_mod',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_prot_gen',
            field=models.DateField(blank=True, null=True, verbose_name='Data prot. gen.'),
        ),
    ]
